apiVersion: v1
kind: Service
metadata:
  name: account-service-db
  labels:
    app: account-service
spec:
  ports:
  - port: 5432
  selector:
    app: account-service
    tier: postgresql
  clusterIP: None
