apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  ports:
  - name: http
    port: 5000
  selector:
    app: account-service
    tier: api
  clusterIP: None
